### ISSUE TITLE
TypeError: window.twttr.widgets is undefined 

### ISSUE THREAD

**Issue by ghankerson** [humanmade/react-oembed-container#11]
Added a PR to patch this  https://github.com/humanmade/react-oembed-container/pull/10

**Comment by kadamwhite** [comment]
Thanks for the patch! I removed the unrelated built code and landed the relevant change as #13 ; going to push a beta release now to let some community colleagues test it out. Apologies for not seeing this ticket until now.

**Comment by ghankerson** [comment]
Wonderful! It's not been a problem  to use my fork but looking forward to getting back into the main repo.
