### ISSUE TITLE
Version 1.0.0 Breaking Changes?

### ISSUE THREAD

**Issue by monsonjeremy** [humanmade/react-oembed-container#17]
Hi,

I was looking at the changelog for version 1.0.0 and there are no listed breaking changes. 
Could you clarify this? If you are following [semver](https://semver.org/) I would expect there to be a breaking change.

Thanks!

**Comment by monsonjeremy** [comment]
@kadamwhite Any comments?

**Comment by kadamwhite** [comment]
I support semver as a general practice but in this case the change was made to declare the software complete and stable, not to indicate any known breaking change.
